/**:
  ros__parameters:
    # Basic setup
    map_frame: map 
    robot_frame: base_link
    max_range: 10.5
    resolution: 0.05
    prob_hit: 0.99
    prob_miss: 0.1
    thres_min: 0.49
    thres_max: 0.51
    map_save_dir: ""

    # Visualizations
    publish_pointcloud: false 
    publish_vis_marker: false 
    visualization_rate: 2.0


    apply_raw_sensor_data: false

    # Remote mapping
    publish_updates: false
    publish_overwrites: false
    publish_sections: false

    remote_sources: [vdb_mapping]
    vdb_mapping:
      namespace: spot_hand_mapping
      apply_remote_updates: false
      apply_remote_overwrites: true
      apply_remote_sections: true
